WpfCalculatrice::MainWindow
PropertyChangedEventHandler PropertyChanged
Referenced by MainWindow.OnPropertyChanged.
double Nb1
Referenced by MainWindow.butDivise_Click, MainWindow.butFact_Click, MainWindow.butMoins_Click, MainWindow.butMultiplie_Click, MainWindow.butPlus_Click.
double Nb2
Referenced by MainWindow.butDivise_Click, MainWindow.butMoins_Click, MainWindow.butMultiplie_Click, MainWindow.butPlus_Click.
double Resultat
Obtient ou définit le résultat de l'opération.
Referenced by MainWindow.butDivise_Click, MainWindow.butFact_Click, MainWindow.butMoins_Click, MainWindow.butMultiplie_Click, MainWindow.butPlus_Click.
bool _contentLoaded
Referenced by MainWindow.InitializeComponent.
double resultat
System Windows Controls Button butDivise
System Windows Controls Button butFact
System Windows Controls Button butMoins
System Windows Controls Button butMultiplie
System Windows Controls Button butPlus
MainWindow()
Initialise une nouvelle instance de la classe MainWindow.
References MainWindow.InitializeComponent.
void InitializeComponent()
InitializeComponent.
References MainWindow._contentLoaded.
Referenced by MainWindow.MainWindow.
void InitializeComponent()
InitializeComponent.
References MainWindow._contentLoaded.
void butDivise_Click(object sender, RoutedEventArgs e)
Gère l'événement de clic pour l'opération de division.
References Calcul.Division, MainWindow.Nb1, MainWindow.Nb2, MainWindow.Resultat.
Referenced by MainWindow.Connect.
void butFact_Click(object sender, RoutedEventArgs e)
Gère l'événement de clic pour l'opération de factorielle.
References Calcul.Factorielle, MainWindow.Nb1, MainWindow.Resultat.
Referenced by MainWindow.Connect.
void butMoins_Click(object sender, RoutedEventArgs e)
Gère l'événement de clic pour l'opération de soustraction.
References MainWindow.Nb1, MainWindow.Nb2, MainWindow.Resultat, Calcul.Soustraction.
Referenced by MainWindow.Connect.
void butMultiplie_Click(object sender, RoutedEventArgs e)
Gère l'événement de clic pour l'opération de multiplication.
References Calcul.Multiplication, MainWindow.Nb1, MainWindow.Nb2, MainWindow.Resultat.
Referenced by MainWindow.Connect.
void butPlus_Click(object sender, RoutedEventArgs e)
Gère l'événement de clic pour l'opération d'addition.
References Calcul.Addition, MainWindow.Nb1, MainWindow.Nb2, MainWindow.Resultat.
Referenced by MainWindow.Connect.
void System.Windows.Markup.IComponentConnector. Connect(int connectionId, object target)
References MainWindow.butDivise_Click, MainWindow.butFact_Click, MainWindow.butMoins_Click, MainWindow.butMultiplie_Click, MainWindow.butPlus_Click.
void System.Windows.Markup.IComponentConnector. Connect(int connectionId, object target)
References MainWindow.butDivise_Click, MainWindow.butFact_Click, MainWindow.butMoins_Click, MainWindow.butMultiplie_Click, MainWindow.butPlus_Click.
void OnPropertyChanged(string name)
Notifie les abonnés qu'une propriété a changé.
name Le nom de la propriété qui a changé.
References MainWindow.PropertyChanged.