Calculatrice::Calcul
static double Addition(double a, double b)
Additionne deux nombres.
a Premier nombre. b Deuxième nombre. La somme de a et b .
Referenced by MainWindow.butPlus_Click.
static double Division(double a, double b)
Divise le premier nombre par le deuxième.
a Numérateur. b Dénominateur (ne doit pas être égal à 0). Le quotient de a et b . DivideByZeroException Lance une exception si b est égal à 0.
Referenced by MainWindow.butDivise_Click.
static double Factorielle(double a)
Calcule la factorielle d'un nombre entier non négatif.
a Nombre entier non négatif. La factorielle de a . ArgumentException Lance une exception si a est négatif ou non entier.
Referenced by MainWindow.butFact_Click.
static double Multiplication(double a, double b)
Multiplie deux nombres.
a Premier nombre. b Deuxième nombre. Le produit de a et b .
Referenced by MainWindow.butMultiplie_Click.
static double Soustraction(double a, double b)
Soustrait le deuxième nombre du premier.
a Premier nombre. b Deuxième nombre. La différence entre a et b .
Referenced by MainWindow.butMoins_Click.