.TH "P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/WpfCalculatrice/obj/Debug/net8.0-windows/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/WpfCalculatrice/obj/Debug/net8.0-windows/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
