.TH "P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/Calculatrice/Calcul.cs" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/Calculatrice/Calcul.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalcul\fP"
.br
.RI "Classe qui gère toutes les opérations arithmétiques de la calculatrice\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCalculatrice\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
