.TH "Calculatrice" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calculatrice
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalcul\fP"
.br
.RI "Classe qui gère toutes les opérations arithmétiques de la calculatrice\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
