.TH "P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/Calculatrice/obj/Debug/net8.0-windows Directory Reference" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/Calculatrice/obj/Debug/net8.0-windows Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v8\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBCalculatrice\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBCalculatrice\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
