.TH "P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/WpfCalculatrice/obj/Debug/net8.0-windows/WpfCalculatrice_uhxupbhu_wpftmp.GlobalUsings.g.cs" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P:/INFO2/S3/R3.04/TD1/WpfCalculatrice/WpfCalculatrice/obj/Debug/net8.0-windows/WpfCalculatrice_uhxupbhu_wpftmp.GlobalUsings.g.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
