.TH "WpfCalculatrice" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WpfCalculatrice
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml\&. "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Logique d'interaction pour la fenêtre principale de l'application\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
