.TH "App" 3 "Version 1.0" "Calculatrice WPF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App \- Interaction logic for App\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application, Application, and Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml\&. 

\fBApp\fP\&. 
.PP
Definition at line \fB42\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB49\fP of file \fBApp\&.g\&.cs\fP\&.
.SS "void InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB49\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.SS "static void Main ()\fR [static]\fP"

.PP
Application Entry Point\&. 
.PP
Definition at line \fB64\fP of file \fBApp\&.g\&.cs\fP\&.
.SS "static void Main ()\fR [static]\fP"

.PP
Application Entry Point\&. 
.PP
Definition at line \fB64\fP of file \fBApp\&.g\&.i\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice WPF from the source code\&.
